import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const platform = await readFile('faro-platform.js', 'utf8');
const index = await readFile('index.html', 'utf8');
const shell = await readFile('app-shell.html', 'utf8');
const sw = await readFile('sw.js', 'utf8');
const build = await readFile('scripts/build-static-site.mjs', 'utf8');
const onboarding = await readFile('faro-onboarding.js', 'utf8');
const onboardingCommit = await readFile('faro-onboarding-commit.js', 'utf8');
const manifest = JSON.parse(await readFile('manifest.webmanifest', 'utf8'));
const icon192 = await readFile('icon-192.png');
const icon512 = await readFile('icon-512.png');

const contains = (source, snippet, label) => assert.equal(source.includes(snippet), true, label);
const pngSize = buffer => {
  assert.equal(buffer.subarray(0, 8).toString('hex'), '89504e470d0a1a0a', 'Arquivo precisa ser PNG válido');
  return [buffer.readUInt32BE(16), buffer.readUInt32BE(20)];
};

contains(platform, 'const INSTALL_GATE_ENFORCED = true', 'Instalação comercial precisa ser obrigatória');
contains(platform, "!app.isStandalone()", 'Gate deve liberar somente o app instalado');
contains(platform, 'Instale o FARO', 'Gate precisa pedir instalação de forma direta');
contains(platform, 'Seu FARO, sempre à mão.', 'Abertura precisa ter identidade sem explicar tecnologia');
contains(platform, 'INSTALAR FARO', 'Android/computador precisam ter ação clara de instalação');
contains(platform, 'Adicionar à Tela de Início', 'iPhone precisa ter tutorial de instalação');
contains(platform, 'SamsungBrowser', 'Samsung Internet precisa de fallback próprio');
contains(platform, 'window.__faroInstallPrompt', 'Plataforma precisa consumir o prompt capturado cedo');
contains(platform, 'waitForInstallPrompt', 'Botão precisa aguardar prompt tardio antes do fallback');
contains(platform, 'prompt.userChoice', 'Gate precisa tratar aceite ou recusa do instalador');
contains(platform, "setAttribute('inert', '')", 'Produto atrás do gate não pode continuar interativo');
contains(platform, "root.dataset.faroPlatformReady = 'true'", 'Interface só pode ser liberada depois da decisão da plataforma');
contains(platform, 'canEnterProduct', 'Onboarding e produto precisam consultar o gate');
contains(onboarding, 'FaroPlatform && !window.FaroPlatform.canEnterProduct()', 'Onboarding não pode começar antes da instalação');

contains(shell, 'data-faro-platform-ready', 'Shell precisa esconder UI até a plataforma ficar pronta');
contains(shell, 'visibility:hidden!important', 'Shell precisa impedir piscada da Home no primeiro frame');
contains(shell, '#onboardingModal:not(:has(#faroFinish)){visibility:hidden!important}', 'Owner legado do onboarding não pode ganhar frame visível');
contains(shell, 'window.__faroInstallPrompt = null', 'Bootstrap precisa preparar captura precoce do instalador');
contains(shell, "window.addEventListener('beforeinstallprompt'", 'Bootstrap precisa capturar o instalador antes da UI');
contains(shell, 'faro-platform.js?v=3', 'Shell precisa carregar a porta de instalação');
contains(shell, 'faro-update.js?v=1', 'Shell precisa carregar a política de atualização silenciosa');
contains(shell, 'faro-home-r2.js?v=2', 'Shell precisa carregar Home premium');
contains(shell, 'faro-register-earnings.js?v=1', 'Shell precisa carregar o helper de ganhos antes do Registro');
contains(shell, 'faro-register.js?v=3', 'Shell precisa carregar a geração premium do Registro');
contains(shell, 'faro-interactions.js?v=2', 'Shell precisa carregar a fundação de interação R3-B');
contains(shell, 'faro-planning.js?v=2', 'Shell precisa carregar o cockpit estrutural R3');
contains(shell, 'faro-r3b.js?v=1', 'Shell precisa carregar a identidade/interação R3-B');
contains(shell, 'faro-r3-routing.js?v=3', 'Shell precisa carregar a geração idempotente da navegação R3-B.3');
contains(shell, 'faro-onboarding.js?v=3', 'Shell precisa carregar a geração do onboarding');
contains(shell, 'faro-onboarding-commit.js?v=1', 'Shell precisa carregar o owner fail-safe do gesto final');
contains(shell, 'faro-tour.js?v=2', 'Shell precisa carregar a geração corrigida do tour');
contains(shell, 'faro-r2-polish.js?v=2', 'Shell precisa carregar Histórico/Central premium');
contains(onboardingCommit, 'original.cloneNode(true)', 'Owner final precisa remover o listener anônimo anterior');
contains(onboardingCommit, "window.dispatchEvent(new CustomEvent('faro:onboarding-complete'))", 'Owner final precisa emitir handoff pós-commit');

assert.equal(manifest.id, './', 'Refresh do splash não pode criar uma segunda identidade de app');
assert.equal(manifest.background_color, '#FFFFFF');
assert.equal(manifest.theme_color, '#FFFFFF');
contains(index, '<meta name="theme-color" content="#FFFFFF">', 'Entrada inicial deve anunciar tema branco ao navegador');
contains(shell, '<meta name="theme-color" content="#FFFFFF">', 'Shell externo deve nascer branco');
contains(shell, 'background:#FFFFFF', 'Primeiro frame/boot guard deve usar fundo branco');
contains(shell, ".replace('<meta name=\"theme-color\" content=\"#0B1121\">', '<meta name=\"theme-color\" content=\"#FFFFFF\">')", 'Transformação do shell legado precisa neutralizar o theme-color escuro antes do primeiro paint');
contains(index, '<link rel="manifest" href="./manifest.webmanifest?v=2">', 'Entrada deve pedir a geração nova do manifest ao Android/Chrome');
contains(shell, '<link rel="manifest" href="./manifest.webmanifest?v=2">', 'Shell deve pedir a mesma geração nova do manifest');
contains(shell, ".replace('<link rel=\"manifest\" href=\"./manifest.webmanifest\">', '<link rel=\"manifest\" href=\"./manifest.webmanifest?v=2\">')", 'Shell final não pode reintroduzir a geração antiga do manifest ao escrever o legado');
contains(sw, "const CORE_CACHE = 'faro-v1-core-23'", 'Geração premium precisa renovar o core cache');
contains(sw, "'./manifest.webmanifest?v=2'", 'PWA deve armazenar a mesma geração versionada do manifest');

contains(sw, 'faro-platform.js?v=3', 'PWA precisa armazenar a mesma geração da porta de instalação');
contains(sw, 'faro-update.js?v=1', 'PWA precisa armazenar a política de atualização silenciosa');
contains(sw, 'faro-home-r2.js?v=2', 'PWA precisa armazenar Home premium');
contains(sw, 'faro-register-earnings.js?v=1', 'PWA precisa armazenar o helper de ganhos');
contains(sw, 'faro-register.js?v=3', 'PWA precisa armazenar Registro premium por plataforma');
contains(sw, 'faro-interactions.js?v=2', 'PWA precisa armazenar a fundação de interação R3-B');
contains(sw, 'faro-planning.js?v=2', 'PWA precisa armazenar Planejar R3');
contains(sw, 'faro-r3b.js?v=1', 'PWA precisa armazenar a camada R3-B');
contains(sw, 'faro-r3-routing.js?v=3', 'PWA precisa armazenar as rotas idempotentes R3-B.3');
contains(sw, 'faro-onboarding.js?v=3', 'PWA precisa armazenar o onboarding');
contains(sw, 'faro-onboarding-commit.js?v=1', 'PWA precisa armazenar o owner fail-safe do gesto final');
contains(sw, 'faro-tour.js?v=2', 'PWA precisa armazenar o tour corrigido');
contains(sw, 'faro-r2-polish.js?v=2', 'PWA precisa armazenar Histórico/Central premium');
for (const asset of ['./assets/platforms/faro-platform-99.svg','./assets/platforms/faro-platform-indrive.svg','./assets/platforms/faro-platform-uber.svg']) contains(sw, asset, `PWA precisa armazenar ${asset}`);
contains(sw, './icon-192.png', 'PWA precisa armazenar ícone 192');
contains(sw, './icon-512.png', 'PWA precisa armazenar ícone 512');
contains(sw, './faro-mark.svg', 'PWA precisa armazenar o símbolo FARO usado pelo splash adaptativo');
contains(build, "'icon-192.png'", 'Build precisa copiar ícone 192');
contains(build, "'icon-512.png'", 'Build precisa copiar ícone 512');
contains(build, "'faro-mark.svg'", 'Build precisa copiar o símbolo FARO usado pelo splash adaptativo');
contains(build, "'faro-register-earnings.js'", 'Build precisa copiar o helper de ganhos');
contains(build, "'assets/platforms/faro-platform-99.svg'", 'Build precisa copiar asset 99');
contains(build, "'assets/platforms/faro-platform-indrive.svg'", 'Build precisa copiar asset inDrive');
contains(build, "'assets/platforms/faro-platform-uber.svg'", 'Build precisa copiar asset Uber');
contains(build, "'faro-interactions.js'", 'Build precisa copiar a fundação de interação R3-B');
contains(build, "'faro-planning.js'", 'Build precisa copiar Planejar R3');
contains(build, "'faro-r3b.js'", 'Build precisa copiar a camada R3-B');
contains(build, "'faro-r3-routing.js'", 'Build precisa copiar rotas R3');
contains(build, "'faro-onboarding-commit.js'", 'Build precisa copiar o owner final do onboarding');
contains(build, "'faro-tour.js'", 'Build precisa copiar o tour');
contains(sw, "event.data?.type === 'FARO_ACTIVATE_WHEN_SAFE'", 'Worker só pode antecipar atualização pelo sinal de saída segura');

const installStart = sw.indexOf("self.addEventListener('install'");
const activateStart = sw.indexOf("self.addEventListener('activate'");
const messageStart = sw.indexOf("self.addEventListener('message'");
assert.ok(installStart >= 0 && activateStart > installStart && messageStart > activateStart, 'Ciclo install/activate/message precisa existir na ordem esperada');
const installBlock = sw.slice(installStart, activateStart);
const activateBlock = sw.slice(activateStart, messageStart);
const messageBlock = sw.slice(messageStart, sw.indexOf('async function externalResponse'));
assert.doesNotMatch(installBlock, /skipWaiting\s*\(/, 'Instalação não pode forçar troca de versão durante uso ativo');
assert.doesNotMatch(activateBlock, /clients\.claim\s*\(/, 'Ativação não pode tomar a página atual do motorista');
assert.match(messageBlock, /FARO_ACTIVATE_WHEN_SAFE[\s\S]*self\.skipWaiting\(\)/, 'Ativação antecipada só pode ocorrer após sinal explícito de saída segura');

assert.deepEqual(pngSize(icon192), [192, 192], 'icon-192.png precisa medir 192×192');
assert.deepEqual(pngSize(icon512), [512, 512], 'icon-512.png precisa medir 512×512');
const manifest192 = manifest.icons.find(icon => icon.src === './icon-192.png');
const manifest512 = manifest.icons.find(icon => icon.src === './icon-512.png');
const maskableMark = manifest.icons.find(icon => icon.src === './faro-mark.svg' && String(icon.purpose || '').split(/\s+/).includes('maskable'));
assert.equal(manifest192?.sizes, '192x192');
assert.equal(manifest512?.sizes, '512x512');
assert.equal(manifest192?.purpose, 'any', 'Ícone opaco 192 não deve ser oferecido como maskable');
assert.equal(maskableMark?.sizes, 'any', 'Símbolo adaptativo deve poder ser rasterizado na resolução exigida pelo Android');
assert.equal(maskableMark?.type, 'image/svg+xml');
assert.ok(maskableMark, 'Manifest precisa oferecer um símbolo FARO dedicado ao recorte maskable do Android');
assert.equal(manifest.display, 'standalone');
assert.equal(manifest.start_url, './app-shell.html');
assert.equal(manifest.prefer_related_applications, false);

assert.doesNotMatch(platform, /continuar no navegador|entrar sem instalar/i, 'Não pode existir bypass comercial visível');
assert.doesNotMatch(platform, /appinstalled[\s\S]{0,500}location\.reload/, 'Instalação concluída não pode criar loop de reload');

console.log('FARO físico: instalação segura, splash adaptativo e geração premium de Registro/Home/Central — ok');
